# Generated by Django 3.0.6 on 2020-06-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addQ',
            fields=[
                ('Question_id', models.AutoField(primary_key=True, serialize=False)),
                ('Enter_the_question', models.CharField(max_length=200)),
                ('Subject', models.CharField(max_length=200)),
                ('Year', models.CharField(max_length=200)),
                ('Marks', models.CharField(max_length=200)),
                ('Module', models.CharField(max_length=200)),
                ('Semester', models.CharField(max_length=200)),
                ('Subject_code', models.CharField(max_length=200)),
            ],
        ),
    ]
