# Generated by Django 3.0.6 on 2020-06-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_addq'),
    ]

    operations = [
        migrations.CreateModel(
            name='add',
            fields=[
                ('questionId', models.AutoField(primary_key=True, serialize=False)),
                ('EnterTheQuestion', models.CharField(max_length=200)),
                ('Subject', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('Marks_alloted', models.CharField(max_length=200)),
                ('Module', models.CharField(max_length=200)),
                ('Semester', models.CharField(max_length=200)),
                ('Subject_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='addQ',
        ),
    ]
