# Generated by Django 3.0.6 on 2020-06-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_auto_20200626_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='EnterTheQuestion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='add',
            name='Marks_alloted',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='add',
            name='Module',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='add',
            name='Semester',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='add',
            name='Subject',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='add',
            name='Subject_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='add',
            name='year',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
