# Generated by Django 3.0.6 on 2020-06-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_auto_20200627_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='DifficultLevel',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Difficult', 'Difficult')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='add',
            name='unitNo',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3')], max_length=200, null=True),
        ),
    ]
